src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LeadType__c</fullName>
        <label>LeadType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>sold to other</fullName>
                </value>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Govt Agency</fullName>
                </value>
                <value>
                    <fullName>Inter-company</fullName>
                </value>
                <value>
                    <fullName>Bankrupt-specific Excluded Creditors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account_matched__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account matched</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Claims (Account matched)</relationshipLabel>
        <relationshipName>MatchedClaims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bankruptcy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field will link the claim to a Bankruptcy on the account object</description>
        <label>Bankruptcy</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Bankruptcy</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disqualify_Reason__c</fullName>
        <label>Disqualify Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Match</fullName>
                </value>
                <value>
                    <fullName>Lead Match</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bankrupcy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bankrupcy</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debtor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Debtor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Debtor)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Account_DisqualifyLeads.cls
public class Account_DisqualifyLeads {
    public static void process(Set<Id> accountIds){
        List<Account> existing_acounts = [SELECT Name, RecordType.Name, LeadType__c , Type, (SELECT Id, Name, Bankrupcy__c, Debtor__c FROM Opportunities) FROM Account WHERE Id IN :accountIds];
        Map<String, Account> existing_account_map = new Map<String, Account>(); //[SELECT Id, Name, RecordType.Name, Type, (SELECT Id, Name, Bankrupcy__c, Debtor__c FROM Opportunities) FROM Account WHERE Name IN :account_name_map.values()];
        for(Account a : existing_acounts){
            existing_account_map.put(a.Name.toUpperCase(), a);
        }
        
        Set<String> disqualified_account_types = new Set<String>{'Bank', 'Competitor', 'Govt Agency'};
            
        List<Lead> leads_to_disqualify = [SELECT Id, Name, Bankruptcy__c, Company, Status FROM Lead WHERE Company IN :existing_account_map.keySet()];
        for(Lead l : leads_to_disqualify){
            system.debug('lead : ' + l);
            Account matching_account;
            if(existing_account_map.containsKey(l.Company.toUpperCase())){
            	matching_account = existing_account_map.get(l.Company.toUpperCase());    
            }
            
            if(matching_account != null){
                System.debug('matching_account.Type: ' + matching_account.Type);
                Boolean is_unqualified_account = (disqualified_account_types.contains(matching_account.Type) || disqualified_account_types.contains(matching_account.LeadType__c)) ;
                Boolean has_opportunity_match = false;
                
                system.debug('check opportunities');
                for(Opportunity o : matching_account.Opportunities){
                    system.debug(o);
                    if(o.Bankrupcy__c == l.Bankruptcy__c ) has_opportunity_match = true;
                }
                
                if(has_opportunity_match || is_unqualified_account){
                    l.Status = 'Unqualified';
                    l.Disqualify_Reason__c = (is_unqualified_account) ? 'Account Match':'Client';
                    l.Account_matched__c = matching_account.Id;
                }
            }
        }
        update leads_to_disqualify;
    }

}