src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LeadType__c</fullName>
        <label>LeadType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>sold to other</fullName>
                </value>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Govt Agency</fullName>
                </value>
                <value>
                    <fullName>Inter-company</fullName>
                </value>
                <value>
                    <fullName>Bankrupt-specific Excluded Creditors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account_matched__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account matched</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Claims (Account matched)</relationshipLabel>
        <relationshipName>MatchedClaims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank</fullName>
                </value>
                <value>
                    <fullName>Bankrupt-specific Excluded Creditors</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Govt Agency</fullName>
                </value>
                <value>
                    <fullName>Inter-company</fullName>
                </value>
                <value>
                    <fullName>sold to other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Bankrupcy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bankrupcy</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debtor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Debtor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Debtor)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Account_TriggerHandler_Test.cls
@isTest
private class Account_TriggerHandler_Test {
    static testmethod void test_simple_lead_conversion(){
        
        Integer numOfLeads = 3;
        String nameOfCompany = 'Test Co';
        List<Lead> test_leads = TestDataFactory.createLeadsWCompanyName(numOfLeads, nameOfCompany);
        for(Lead l : test_leads){
            l.Type__c = 'Competitor';
        }
        insert test_leads;
        
        test.StartTest();
		List<Lead> leadList = [SELECT Id, Company FROM Lead];
        
        System.assertEquals(numOfLeads, leadList.size());
        
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(test_leads[0].Id);
        LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());
        
        List<Opportunity> new_opps = [SELECT Id, Name, Bankrupcy__c , Debtor__c  FROM Opportunity];
        System.debug('new_opps');
        System.debug(new_opps);
        
        List<account> accounts = [SELECT Id, Name, RecordType.Name, Type, LeadType__c  FROM Account];
        System.debug('accounts');
        System.debug(accounts);
        
        List<Lead> leads_now = [SELECT Id, Name, Status FROM Lead];
        System.debug('leads_now');
        System.debug(leads_now);
        
        
        List<Lead> convertedLeadList = [SELECT Id, Company, Status, Account_matched__c FROM Lead WHERE Status = 'Unqualified'];
        System.assertEquals(numOfLeads - 1, convertedLeadList.size());
        
        test.stopTest();
        
    }
    

}