src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Bankruptcy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field will link the claim to a Bankruptcy on the account object</description>
        <label>Bankruptcy</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Bankruptcy</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Claimed_Total__c</fullName>
        <formula>Admin503B_Claimed_Amount__c + Admin_Claimed_Amount__c + Priority_Claimed_Amount__c + Secured_Claimed_Amount__c + Unsecured_Claimed_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Claimed Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Debtor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field will populate the debtor account name.</description>
        <label>Debtor Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Debtors</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Claims (Debtor Name)</relationshipLabel>
        <relationshipName>Claims_relation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Claim_Number__c</fullName>
        <externalId>true</externalId>
        <label>External Claim Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scheduled_Total__c</fullName>
        <formula>Admin503B_Scheduled_Amount__c + Admin_Scheduled_Amount__c + Priority_Scheduled_Amount__c + Secured_Scheduled_Amount__c + Unsecured_Scheduled_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scheduled Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/MyLeadController.cls
public with sharing class MyLeadController {
    @AuraEnabled
    public static List<Lead> findLeads (Id recordId) {
        Lead clead = [SELECT Bankruptcy__c,Company FROM Lead WHERE Id=:recordId];
        String leadBankruptcy = clead.Bankruptcy__c;
 		String Company = clead.Company;
        List<Lead> similarLeads = getSimilarLeads(recordId, Company, leadBankruptcy);
        return similarLeads;
    }
    private static List<Lead> getSimilarLeads (Id recordId, String Company, String leadBankruptcy) {
    
    return [
            SELECT Id, status, Scheduled_Total__c, LeadSource, Claimed_Total__c , External_Claim_Number__c, company, Bankruptcy__c, Debtor_Name__c 
            FROM Lead WHERE Id != :recordId AND Company =:Company AND Bankruptcy__c =:leadBankruptcy
        ];
    }
}